import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";
export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn-icons.flaticon.com/png/512/2504/premium/2504739.png?token=exp=1642418022~hmac=a0f208b1a6b43127d89afec2c964920a"
        />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left Section */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* Right Section */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          <ViewGridIcon
            className="
          h-10 
          w-10 
          p-2 
          rounded-full 
          hover:bg-gray-100 
          cursor-pointer"
          />

          <Avatar url="https://lh3.googleusercontent.com/ogw/ADea4I6-no__D_swt0_wUzQ857BqQzHvKo1CoFarJYNB=s83-c-mo" />
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          alt="google-banner-image"
          height={100}
          width={300}
        />
        <div
          className="
        flex
        w-full
        mt-5 
        hover:shadow-lg 
        focus-within:shadow-lg 
        rounded-full 
        border border-gray-200
        px-5 
        py-3 
        items-center
        max-w-md
        sm:max-w-xl 
        lg:max-w-2xl"
        >
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm: space-x-4">
          <button onClick={search} className="btn">
            Google Search
          </button>

          <button onClick={search} className="btn">
            Im Feeling Lucky
          </button>
        </div>
      </form>

      <Footer />
    </div>
  );
}
